### ISSUE TITLE
WhatsApp Group

### ISSUE THREAD

**Issue by karkouri990** [Jieyab89/OSINT-Cheat-sheet#10]
[WhatsApp Group](https://whatsappgroup.info/)

**Comment by Jieyab89** [comment]
Let me check

**Comment by Jieyab89** [comment]
Thanks for submit issue, update here the commit 
https://github.com/Jieyab89/OSINT-Cheat-sheet/commit/2b0c63a21e724c04d92f508847bc0f439c8a90f6 
Thanks

**Comment by Jieyab89** [comment]
Hi @karkouri990 

The domain cannot access, if you are dev please update and fix it. Reply this issue
