### ISSUE TITLE
Can you add Instagram private profile viewer?

### ISSUE THREAD

**Issue by Narukklady** [Jieyab89/OSINT-Cheat-sheet#5]
How i can profiling Instagram private account can you add recommendation tool

**Comment by Jieyab89** [comment]
Thank you for submit issue, last year looking at my Instagram private profile I had a private tool that I could use, but for now the tool I use can't work, the API service provider is dead (turned of), I haven't found another method for this. And some of the tools that I used to try also can't be used anymore. If you want to see that Instagram profile for now you can do social e to the target, create organic sockpuppet, pay brokers (followers, service providers)

I don't recommend you to try Instagram web based private tools which will later ask for human verification, most of them don't work. Therefore I prefer to use toutatis, this tool is available on Github. Most Instagram viewer tools need to do session ID or account authentication (Use fake Instagram)

Right now I don't have time to look for new methods (development tools private), try new tools, recommend good tools, but you can use toutatis for a while. If I have free time then I will try to find new methods and tools that I will try and recommend, I will update you via Github

Tips:

View ID IG : https://codeofaninja.com/tools/find-instagram-user-id

View loc : https://github.com/bellingcat/instagram-location-search

Insta extract info : https://github.com/instaloader/instaloader

If you want to do anonymous profiling, many web-based tools are available but do not support private accounts. I'll check and recheck this repo and add something new

Thanks

**Comment by Narukklady** [comment]
Thank you for the answer, i appreciate it, i’m waiting for your update

**Comment by MasJuna** [comment]
> How i can profiling Instagram private account can you add recommendation tool

Same here, very difficult if you has found share please

**Comment by Jieyab89** [comment]
https://github.com/Jieyab89/OSINT-Cheat-sheet-/commits/main 

Check my commit today, i was added new resources about Insta and anything

**Comment by Jieyab89** [comment]
Try using instaloader, i was try 2020 when i use this can extract photos and more including private account. In 2023 I don't know if this still works, I haven't used it again

![try 2](https://user-images.githubusercontent.com/71226310/211864897-b9928fcc-ad9d-478c-9fe6-396306e62aec.jpg)
![try 1](https://user-images.githubusercontent.com/71226310/211864909-207eaa83-c2df-4934-9475-3c94a7b320c9.jpg)

You can see on my images. I just found this file, it's an old laptop. I rarely use it, if the instaloader can extract it let me know 

Thanks, sorry if my answer is not very helpful

**Comment by Jieyab89** [comment]
You can check here : https://github.com/instaloader/instaloader/issues 

Sorry if I don't provide much information, and I didn't try. I don't have time to do this :(

**Comment by Jieyab89** [comment]
> if you want to see a private instagram account. Login first using secondary Instagram and follow the account until access is granted. then use the option --username --password to login as your secondary account. Then you can download all json, highlights, and feeds from that account. i already did this to my ex girlfriend's account :)

Thanks for help this issue. @Narukklady do you was try it?

**Comment by Jieyab89** [comment]
Join on my forum platform here: https://forum.seccodeid.com/register
