### ISSUE TITLE
Outdated TraceLabs Slack link

### ISSUE THREAD

**Issue by belouve** [Jieyab89/OSINT-Cheat-sheet#6]
Hi, I noticed that the repository has an outdated link to the TraceLabs Slack. TraceLabs now has a Discord server. Here's the updated link to join the Discord: [Discord Invite Link](https://discord.gg/tracelabs)

Please consider updating the link in the repository. Thank you!

**Comment by Jieyab89** [comment]
Hallo @belouve 

Thank you for the information, I will update it and if you are interested you can contributing
