### ISSUE TITLE
Help Maltego Transform and Add Holehe Maltego Transform

### ISSUE THREAD

**Issue by KepitingKikir991** [Jieyab89/OSINT-Cheat-sheet#9]
I want to try this Hoelehe transform in Maltego, try to install and import this transform in local machine but I have error problem while running this transform help im struggle thanks for helping 

About this transform 

Can investigate social media used with email. This transform works by resetting passwords through social media platforms

![err-1](https://github.com/Jieyab89/OSINT-Cheat-sheet/assets/132563479/db701263-1269-4ec3-9684-87fefe9e0611)
![err-2](https://github.com/Jieyab89/OSINT-Cheat-sheet/assets/132563479/3bf8055d-8cf8-427d-a648-3c6fd699dd55)
![image](https://github.com/Jieyab89/OSINT-Cheat-sheet/assets/132563479/d2a02d0c-6d5d-46ef-bdbd-a707e5f12ea5)
![image](https://github.com/Jieyab89/OSINT-Cheat-sheet/assets/132563479/e445816e-ebb3-41bf-8c22-43632bd1ef04)
![image](https://github.com/Jieyab89/OSINT-Cheat-sheet/assets/132563479/c8328236-f55a-44cf-8890-9355c01c602e)

Whats wrong? Any can help? 

You can try and add this on your repo. I wanna see your review 

Github : https://github.com/megadose/holehe-maltego

**Comment by Jieyab89** [comment]
Allo 

Thanks for submit issue and more resources. This is a great transform, if you want to install according to the environment you are using make sure Python is executable and make the script to run (cli command) you can see the transofrm documentation

https://github.com/megadose/holehe-maltego/tree/master/Misc/installation-image

Or visiting in the Maltego doc

https://docs.maltego.com/support/solutions/articles/15000017605-local-transforms-example-

I want to try it but not now, I still have work to finish, if I try I will reply, add this resource and inform to you

**Note: If you still have problems installing, you can create an issue in the developer repo**

Thanks
